// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(StudentsContext))]
    [Migration("20221012190601_AdjustSeed")]
    partial class AdjustSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Model.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tb_estudantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "999.888.777-66",
                            Email = "douglas@email.com",
                            Name = "Douglas Oliveira"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "555.333.222-11",
                            Email = "Paula@email.com",
                            Name = "Paula Souza"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "111.222.444-55",
                            Email = "jao@email.com",
                            Name = "João Silva"
                        },
                        new
                        {
                            Id = 4,
                            CPF = "333.222.888-66",
                            Email = "mari@email.com",
                            Name = "Marina Miranda"
                        },
                        new
                        {
                            Id = 5,
                            CPF = "444.333.009-88",
                            Email = "souza@email.com",
                            Name = "Maurício Souza"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
